name: Build and Publish Docker Image

on:
  push:
    branches: [main]

env:
  IMAGE_NAME: mohakbajaj/xebiaDemoImage
jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'

    - name: Build with Maven
      run: mvn package

    - name: Build Docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: ${{ env.IMAGE_NAME }}:latest
        builder: docker://maven:3.8.2-jdk-11
        build-args: |
          MAVEN_OPTS="-Dmaven.repo.local=/github/workspace/.m2/repository"
          JAR_FILE=target/*.jar

    - name: Logout from DockerHub
      run: docker logout

    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Push Docker image to DockerHub
      run: docker push ${{ env.IMAGE_NAME }}:latest
